POST  http://localhost:5006/api
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InJlYWxVc2VyIjp7ImlkIjoxLCJ1ZXNybmFtZSI6InN1cmFqa2FybmEiLCJlbWFpbCI6InN1cmFqa2FybmFAZ21haWwuY29tIn0sImlhdCI6MTcwNjAwMzU0Nn0sImlhdCI6MTcwNjAwMzYwOCwiZXhwIjoxNzA2MDAzNjM4fQ.-plclIp-7vdrS4jZSTYplRNCUplqvVpeKzEJwLlwCMs
###


POST http://localhost:5006/api/protected
Content-Type: application/json

{
    "name":"suraj"
}

###

POST http://localhost:5006/api/login
Content-Type: application/json

{
    "uesrname":"mukeshkarna",
    "password":"2345"
}



###
POST http://localhost:5006/api/regenerate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsVXNlciI6eyJpZCI6MSwidWVzcm5hbWUiOiJzdXJhamthcm5hIiwiZW1haWwiOiJzdXJhamthcm5hQGdtYWlsLmNvbSJ9LCJpYXQiOjE3MDYwMDM1NDZ9.OEb84HkUvGQZX7PMWnNd2pbcMFxfGhTfzOQpiWq-sS8


###
POST http://localhost:5006/api/register
Content-Type: application/json

{
    "username":"suraj",
    "password":"anything",
    "confirmPassword":"anything"
}



